### ISSUE TITLE
Upgrade dbt-core to >= 1.6.0

### ISSUE THREAD

**Issue by dallmkp** [re-data/re-data#402]
**Tell us about the problem you're trying to solve**

I would like to upgrade to dbt-core 1.6.0.

**Describe the solution you’d like**

re_data is pinned to less than 1.6. I would like to see 1.6 to be allowed.

See https://github.com/re-data/re-data/blob/master/setup.py#L33

**Describe the alternative you’ve considered or used**

I'd have to disable re_data from my stack, but I would like to avoid that.

**Comment by famazak** [comment]
Hey @mateuszklimek - I see there was a recent change ([commit](https://github.com/re-data/re-data/commit/bc96606b0b3e1f61721d223a13ec1abf7b64d8f5)) that adjusted the dbt-core pin, but when I install re_data alongside dbt-core, pip's dependency resolver only installs dbt-core 1.5.8 when the latest version is 1.6.6 since re_data 0.10.8 (the latest release on pypi) is still pinned to <1.6.0

Could you publish a new release to pypi?  Thank you!

**Comment by famazak** [comment]
@mateuszklimek I'm bumping this one more time hoping to get an update on whether or not a new release can be pushed.  Thanks!

**Comment by davidzajac1** [comment]
@dallmkp @famazak the release of 0.10.9 supports up to dbt-core 1.7: https://github.com/re-data/dbt-re-data/releases/tag/0.10.9

Sorry for the long wait time on this one, the project is back on track now.
