### ISSUE TITLE
Add options to specify thresholds for alerts

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#62]
## What

Currently all alerting is based on zscore, but it was couple times mentioned that possibility to manually adjust 
thresholds for alerting would be useful. Also in the future, we expect to have also different anomaly mechanism possible for tables.

## How

This can be done by modifying check and adding new_column: `alerts` there.
Json for this column could look like this:

```
{
  'column_name': {
    'metric_name': {
      'check_for_anomly': 'redata.alerts.thresholds'
      'params': {
        'max': value
        'min': value
     }
    }
  }
}
```
Current code will assume that if that's not defined it normally runs z_score, but it gives possible to run other alerting functions in the future.

**Comment by hishoss** [comment]
I'm really interested in this. We'll have to abstract the current `redata.alerts.base.alert_on_z_score`. For starters, this can be a function/class that accepts:
1. the current inputs 
2. a function of type `(Iterable[Float], Dict[?]) -> Float`
3. a params argument(which holds thresholds, etc) that is consumed by the function in (2)

This approach should allow for having a library of custom anomaly detectors that anyone can contribute to without worrying about  redata itself.

Another interesting thing is to return the values which are anomalous. Not sure how to approach this because it may not be a scalable solution if for example the anomaly detection is backed by SQL and the dataset is huge.

**Comment by mateuszklimek** [comment]
Yep, exactly for abstracting away `alerts_on_z_score`. Not sure that function you mentioned should return `Float` I mean I expected it will be returning Bool (alerting or not) optionally with some description of alert?

And actually one more thing here for returning values which are anomalous. As I understand this problem of huge datasets should not be appearing here. I mean those datasets which we are looking for anomalies in are already results of some Redata checks. (Like daily number of rows added etc.) so it shouldn't be huge number of those values gathered. (It will be just 1 or 24 (in case of hourly processing) new values per tracked metric added daily. Correct?

**Comment by mateuszklimek** [comment]
Changes in how re_data works make this not actual (but possibly could still be implemented in dbt package)
